#   CARREGAR BANCO DE DADOS.

#   JANELA DE ENTRADA DA CAIXA POUPANÇA (LOGIN).

#   SE NAO, FAZER CONTA.

#   SE SIM, VALIDA-LA.

#   OPCOES DO BANCO (JANELA DO BANCO): DEPOSITAR, SACAR, CONSULTAR RENDIMENTOS, SAIR    OPCAO SECRETA PARA DEVS: 12112006 - FUNCAO: APAGAR TODAS CONTAS CADASTRADAS.

#   FAZER ATUALIZACAO DA CONTA PARA PROCIMA CONSULTA.
